import 'dart:async';

import 'package:your_finance_flutter/core/models/bonus_item.dart';
import 'package:your_finance_flutter/core/models/budget.dart';
import 'package:your_finance_flutter/core/models/transaction.dart';
import 'package:your_finance_flutter/core/services/storage_service.dart';

/// 自动交易服务 - 处理定期工资和奖金交易的自动生成
class AutoTransactionService {
  AutoTransactionService._();
  static AutoTransactionService? _instance;
  static final _storageService = StorageService.getInstance();

  static Future<AutoTransactionService> getInstance() async {
    _instance ??= AutoTransactionService._();
    return _instance!;
  }

  /// 生成当月的工资交易
  Future<void> generateMonthlySalaryTransaction({
    required SalaryIncome salaryIncome,
    required int year,
    required int month,
  }) async {
    final storageService = await _storageService;
    final transactionDate = DateTime(year, month, salaryIncome.salaryDay);

    // 计算当月总工资（基本工资 + 津贴）
    final monthlySalary = salaryIncome.basicSalary +
        salaryIncome.housingAllowance +
        salaryIncome.mealAllowance +
        salaryIncome.transportationAllowance +
        salaryIncome.otherAllowance;

    // 创建工资收入交易
    final salaryTransaction = Transaction(
      id: 'salary_${salaryIncome.id}_${year}_$month',
      fromAccountId: 'default', // TODO: 获取用户默认账户
      amount: monthlySalary,
      category: TransactionCategory.salary,
      type: TransactionType.income,
      date: transactionDate,
      description: '${salaryIncome.name} - $month月工资',
      isAutoGenerated: true,
    );

    // 保存工资交易
    await storageService.saveTransactions([salaryTransaction]);

    // 生成奖金交易
    for (final bonus in salaryIncome.bonuses) {
      await _generateBonusTransaction(bonus, year, month, salaryIncome);
    }
  }

  /// 生成奖金交易
  Future<void> _generateBonusTransaction(
    BonusItem bonus,
    int year,
    int month,
    SalaryIncome salaryIncome,
  ) async {
    final storageService = await _storageService;

    // 检查奖金是否应该在当前月份发放
    if (!_shouldGenerateBonusTransaction(bonus, year, month)) {
      return;
    }

    final transactionDate = _getBonusTransactionDate(bonus, year, month);

    final bonusTransaction = Transaction(
      id: 'bonus_${bonus.id}_${year}_$month',
      fromAccountId: 'default', // TODO: 获取用户默认账户
      amount: bonus.amount,
      category: TransactionCategory.bonus,
      type: TransactionType.income,
      date: transactionDate,
      description: '${bonus.typeDisplayName} - ${salaryIncome.name}',
      isAutoGenerated: true,
    );

    // 保存奖金交易
    await storageService.saveTransactions([bonusTransaction]);
  }

  /// 检查是否应该生成奖金交易
  bool _shouldGenerateBonusTransaction(BonusItem bonus, int year, int month) {
    switch (bonus.frequency) {
      case BonusFrequency.oneTime:
        // 一次性奖金：检查发放日期是否在当前月份
        return bonus.startDate.year == year && bonus.startDate.month == month;

      case BonusFrequency.annual:
        // 年度奖金：每年在指定月份发放
        return bonus.startDate.month == month;

      case BonusFrequency.monthly:
        // 月度奖金：每月发放
        return true;

      case BonusFrequency.quarterly:
        // 季度奖金：每季度发放
        final quarters = [1, 4, 7, 10]; // 季度起始月份
        return quarters.contains(month);

      case BonusFrequency.semiAnnual:
        // 半年奖金：每半年发放
        return month == 6 || month == 12;

      default:
        return false;
    }
  }

  /// 获取奖金交易日期
  DateTime _getBonusTransactionDate(BonusItem bonus, int year, int month) {
    switch (bonus.frequency) {
      case BonusFrequency.oneTime:
        return bonus.startDate;

      case BonusFrequency.annual:
        return DateTime(year, bonus.startDate.month, bonus.startDate.day);

      case BonusFrequency.monthly:
        return DateTime(year, month, bonus.startDate.day);

      case BonusFrequency.quarterly:
        // 季度奖金使用季度起始日期
        final quarters = [1, 4, 7, 10];
        final quarterMonth = quarters.firstWhere(
          (q) => q <= month,
          orElse: () => quarters.last,
        );
        return DateTime(year, quarterMonth, 15);

      case BonusFrequency.semiAnnual:
        // 半年奖金使用半年起始日期
        final semiMonth = month <= 6 ? 6 : 12;
        return DateTime(year, semiMonth, 15);

      default:
        return DateTime(year, month, 15);
    }
  }

  /// 检查指定月份是否已有交易，避免重复生成
  Future<bool> hasTransactionForMonth(
    String incomeId,
    int year,
    int month,
  ) async {
    final storageService = await _storageService;
    final transactions = await storageService.loadTransactions();

    return transactions.any(
      (transaction) =>
          transaction.id.contains('salary_${incomeId}_${year}_$month') ||
          transaction.id.contains('bonus_${incomeId}_${year}_$month'),
    );
  }

  /// 为所有活跃的工资收入生成当月交易
  Future<void> generateAllMonthlyTransactions(int year, int month) async {
    final storageService = await _storageService;
    final salaryIncomes = await storageService.loadSalaryIncomes();

    for (final salaryIncome in salaryIncomes) {
      // 检查是否已有交易，避免重复生成
      if (!await hasTransactionForMonth(salaryIncome.id, year, month)) {
        await generateMonthlySalaryTransaction(
          salaryIncome: salaryIncome,
          year: year,
          month: month,
        );
      }
    }
  }
}
