import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';
import 'package:your_finance_flutter/core/models/asset_item.dart';
import 'package:your_finance_flutter/core/models/transaction.dart';
import 'package:your_finance_flutter/core/services/data_migration_service.dart';

/// 数据迁移测试脚本
/// 用于测试数据迁移功能是否正常工作
void main() async {
  print('🧪 开始数据迁移测试...');

  // 初始化SharedPreferences
  final prefs = await SharedPreferences.getInstance();

  // 清理旧数据
  await prefs.clear();
  print('🗑️ 已清理旧数据');

  // 创建模拟的旧格式数据
  await _createMockOldData(prefs);

  // 测试数据迁移
  await _testMigration(prefs);

  // 验证迁移结果
  await _verifyMigrationResults(prefs);

  print('✅ 数据迁移测试完成');
}

/// 创建模拟的旧格式数据
Future<void> _createMockOldData(SharedPreferences prefs) async {
  print('📝 创建模拟旧格式数据...');

  // 资产数据：使用旧的fixedAssets分类
  final oldAssets = [
    {
      'id': 'asset_1',
      'name': '测试房产',
      'amount': 1000000.0,
      'category': 'fixedAssets', // 旧格式
      'subCategory': '房产(自住)',
      'creationDate': DateTime.now().toIso8601String(),
      'updateDate': DateTime.now().toIso8601String(),
      'purchaseDate':
          DateTime.now().subtract(const Duration(days: 365)).toIso8601String(),
      'depreciationMethod': 'straightLine',
      'depreciationRate': 0.02,
      'currentValue': 980000.0,
      'isIdle': false,
      'idleValue': null,
      'notes': '测试房产',
    },
    {
      'id': 'asset_2',
      'name': '测试现金',
      'amount': 50000.0,
      'category': 'liquidAssets', // 这个是正确的
      'subCategory': '银行活期',
      'creationDate': DateTime.now().toIso8601String(),
      'updateDate': DateTime.now().toIso8601String(),
      'purchaseDate': null,
      'depreciationMethod': 'none',
      'depreciationRate': null,
      'currentValue': null,
      'isIdle': false,
      'idleValue': null,
      'notes': '测试现金',
    },
  ];

  // 交易数据：使用旧的TransactionType
  final oldTransactions = [
    {
      'id': 'transaction_1',
      'description': '工资收入',
      'amount': 10000.0,
      'type': 'income', // 旧格式
      'category': 'salary',
      'subCategory': null,
      'fromAccountId': null,
      'toAccountId': 'account_1',
      'envelopeBudgetId': null,
      'date': DateTime.now().toIso8601String(),
      'notes': null,
      'tags': <String>[],
      'status': 'confirmed',
      'isRecurring': false,
      'recurringRule': null,
      'parentTransactionId': null,
      'creationDate': DateTime.now().toIso8601String(),
      'updateDate': DateTime.now().toIso8601String(),
      'imagePath': null,
      'isAutoGenerated': false,
    },
    {
      'id': 'transaction_2',
      'description': '购物支出',
      'amount': 500.0,
      'type': 'expense', // 旧格式
      'category': 'shopping',
      'subCategory': null,
      'fromAccountId': 'account_1',
      'toAccountId': null,
      'envelopeBudgetId': null,
      'date': DateTime.now().toIso8601String(),
      'notes': null,
      'tags': <String>[],
      'status': 'confirmed',
      'isRecurring': false,
      'recurringRule': null,
      'parentTransactionId': null,
      'creationDate': DateTime.now().toIso8601String(),
      'updateDate': DateTime.now().toIso8601String(),
      'imagePath': null,
      'isAutoGenerated': false,
    },
  ];

  // 保存到SharedPreferences
  await prefs.setString('assets_data', jsonEncode(oldAssets));
  await prefs.setString('transactions_data', jsonEncode(oldTransactions));

  print('✅ 模拟旧数据创建完成');
}

/// 测试数据迁移
Future<void> _testMigration(SharedPreferences prefs) async {
  print('🔄 开始测试数据迁移...');

  final migrationService = await DataMigrationService.getInstance();

  // 执行迁移
  await migrationService.checkAndMigrateData();

  print('✅ 数据迁移测试执行完成');
}

/// 验证迁移结果
Future<void> _verifyMigrationResults(SharedPreferences prefs) async {
  print('🔍 验证迁移结果...');

  // 验证资产数据迁移
  final assetsJson = prefs.getString('assets_data');
  if (assetsJson != null) {
    final assets = jsonDecode(assetsJson) as List<dynamic>;

    for (final assetJson in assets) {
      final asset = AssetItem.fromJson(assetJson as Map<String, dynamic>);

      print('📊 资产: ${asset.name}');
      print('   原始分类: ${assetJson['category']}');
      print('   迁移后分类: ${asset.category.name}');

      // 验证分类是否正确迁移
      if (asset.name == '测试房产') {
        assert(asset.category.name == 'realEstate', '房产分类迁移失败');
        print('   ✅ 房产分类迁移成功');
      } else if (asset.name == '测试现金') {
        assert(asset.category.name == 'liquidAssets', '现金分类应该保持不变');
        print('   ✅ 现金分类保持正确');
      }
    }
  }

  // 验证交易数据迁移
  final transactionsJson = prefs.getString('transactions_data');
  if (transactionsJson != null) {
    final transactions = jsonDecode(transactionsJson) as List<dynamic>;

    for (final transactionJson in transactions) {
      final transaction =
          Transaction.fromJson(transactionJson as Map<String, dynamic>);

      print('💸 交易: ${transaction.description}');
      print('   原始类型: ${transactionJson['type']}');
      print('   迁移后流向: ${transaction.flow?.name ?? '未设置'}');

      // 验证流向是否正确推断
      if (transaction.description == '工资收入') {
        assert(
          transaction.flow == TransactionFlow.externalToWallet,
          '收入流向推断失败',
        );
        print('   ✅ 收入流向推断成功');
      } else if (transaction.description == '购物支出') {
        assert(
          transaction.flow == TransactionFlow.walletToExternal,
          '支出流向推断失败',
        );
        print('   ✅ 支出流向推断成功');
      }
    }
  }

  // 验证迁移版本
  final version = prefs.getInt('data_migration_version');
  print('📋 当前数据版本: $version');
  assert(version == 2, '版本号未正确更新');

  print('✅ 迁移结果验证完成，所有测试通过！');
}
