import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:your_finance_flutter/core/models/expense_plan.dart';
import 'package:your_finance_flutter/core/models/transaction.dart';
import 'package:your_finance_flutter/core/providers/account_provider.dart';
import 'package:your_finance_flutter/core/providers/asset_provider.dart';
import 'package:your_finance_flutter/core/providers/budget_provider.dart';
import 'package:your_finance_flutter/core/providers/expense_plan_provider.dart';
import 'package:your_finance_flutter/core/providers/transaction_provider.dart';
import 'package:your_finance_flutter/core/services/total_assets_service.dart';
import 'package:your_finance_flutter/core/theme/app_design_tokens.dart';
import 'package:your_finance_flutter/core/theme/app_theme.dart';
import 'package:your_finance_flutter/core/widgets/app_animations.dart';
import 'package:your_finance_flutter/core/widgets/app_card.dart';
import 'package:your_finance_flutter/core/widgets/app_empty_state.dart';
import 'package:your_finance_flutter/features/transaction_flow/screens/transaction_detail_screen.dart';
import 'package:your_finance_flutter/features/transaction_flow/widgets/global_fab.dart';

/// Dashboard首页 - 财务驾驶舱
/// 显示核心指标、待办事项、最近交易
class DashboardHomeScreen extends StatefulWidget {
  const DashboardHomeScreen({super.key});

  @override
  State<DashboardHomeScreen> createState() => _DashboardHomeScreenState();
}

class _DashboardHomeScreenState extends State<DashboardHomeScreen> {
  @override
  Widget build(BuildContext context) => Scaffold(
        backgroundColor: AppDesignTokens.primaryBackground(context),
        body: RefreshIndicator(
          onRefresh: _refreshData,
          child: SingleChildScrollView(
            physics: const AlwaysScrollableScrollPhysics(),
            padding: EdgeInsets.all(AppDesignTokens.spacing16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // 顶部：财务健康胶囊
                _buildFinancialHealthCapsule(context),

                SizedBox(height: AppDesignTokens.spacing16),

                // 中部：待办事项
                _buildActionableItems(context),

                SizedBox(height: AppDesignTokens.spacing16),

                // 下部：最近交易
                _buildRecentTransactions(context),
              ],
            ),
          ),
        ),
        floatingActionButton: const GlobalFAB(),
      );

  /// 构建财务健康胶囊
  Widget _buildFinancialHealthCapsule(BuildContext context) =>
      Consumer3<AssetProvider, BudgetProvider, TransactionProvider>(
        builder: (context, assetProvider, budgetProvider, transactionProvider,
            child) {
          // 计算净资产
          final accounts = context.read<AccountProvider>().activeAccounts;
          final envelopeBudgets = budgetProvider.getCurrentEnvelopeBudgets();
          final transactions = transactionProvider.transactions;

          final totalAssets = TotalAssetsService.calculateTotalAssets(
            accounts: accounts,
            envelopeBudgets: envelopeBudgets,
            transactions: transactions,
            accountProvider: context.read<AccountProvider>(),
          );

          // 计算本月结余
          final now = DateTime.now();
          final startOfMonth = DateTime(now.year, now.month);
          final monthTransactions = transactions
              .where(
                (t) =>
                    t.status != TransactionStatus.draft &&
                    (t.date.isAfter(startOfMonth) ||
                        t.date.isAtSameMomentAs(startOfMonth)),
              )
              .toList();

          double totalIncome = 0;
          double totalExpense = 0;
          for (final transaction in monthTransactions) {
            if (transaction.isAutoGenerated == true) continue;
            if (transaction.type == TransactionType.income ||
                (transaction.type == null && transaction.category.isIncome)) {
              totalIncome += transaction.amount;
            } else if (transaction.type != TransactionType.transfer) {
              totalExpense += transaction.amount;
            }
          }
          final monthlyBalance = totalIncome - totalExpense;

          // 计算本月剩余预算
          final totalBudget = budgetProvider.calculateTotalBudgetAllocated();
          final totalSpent = budgetProvider.calculateTotalBudgetSpent();
          final remainingBudget = totalBudget - totalSpent;
          final budgetProgress = totalBudget > 0 ? totalSpent / totalBudget : 0.0;

          return AppCard(
            child: Column(
              children: [
                // 净资产行
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          '净资产',
                          style: AppTextStyles.bodySmall(context),
                        ),
                        SizedBox(height: AppDesignTokens.spacing4),
                        Row(
                          children: [
                            Text(
                              context.formatAmount(totalAssets),
                              style: AppTextStyles.headlineMedium(context).copyWith(
                                fontWeight: AppDesignTokens.fontWeightBold,
                                color: totalAssets >= 0
                                        ? AppDesignTokens.successColor(context)
                                    : AppDesignTokens.errorColor,
                              ),
                            ),
                            SizedBox(width: AppDesignTokens.spacing8),
                            Icon(
                              Icons.visibility_outlined,
                              size: AppDesignTokens.iconSizeSmall,
                              color: AppDesignTokens.secondaryText(context),
                            ),
                          ],
                        ),
                      ],
                    ),
                    // 本月结余
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.end,
                      children: [
                        Text(
                          '本月结余',
                          style: AppTextStyles.bodySmall(context),
                        ),
                        SizedBox(height: AppDesignTokens.spacing4),
                        Text(
                          context.formatAmount(monthlyBalance),
                          style: AppTextStyles.displayMedium(context).copyWith(
                            fontSize: AppDesignTokens.fontSize24,
                            fontWeight: AppDesignTokens.fontWeightBold,
                            color: monthlyBalance >= 0
                                        ? AppDesignTokens.successColor(context)
                                : AppDesignTokens.errorColor,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),

                SizedBox(height: AppDesignTokens.spacing16),

                // 预算进度条
                if (totalBudget > 0) ...[
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        '本月预算',
                        style: AppTextStyles.bodySmall(context),
                      ),
                      Text(
                        '剩余 ${context.formatAmount(remainingBudget)}',
                        style: AppTextStyles.bodySmall(context).copyWith(
                          color: remainingBudget > 0
                                        ? AppDesignTokens.successColor(context)
                              : AppDesignTokens.errorColor,
                          fontWeight: AppDesignTokens.fontWeightMedium,
                        ),
                      ),
                    ],
                  ),
                  SizedBox(height: AppDesignTokens.spacing8),
                  ClipRRect(
                    borderRadius: BorderRadius.circular(AppDesignTokens.borderRadius4),
                    child: LinearProgressIndicator(
                      value: budgetProgress.clamp(0.0, 1.0),
                      minHeight: 8,
                      backgroundColor: AppDesignTokens.dividerColor(context),
                      valueColor: AlwaysStoppedAnimation<Color>(
                        budgetProgress < 0.7
                                        ? AppDesignTokens.successColor(context)
                            : budgetProgress < 0.9
                                ? AppDesignTokens.warningColor
                                : AppDesignTokens.errorColor,
                      ),
                    ),
                  ),
                ],
              ],
            ),
          );
        },
      );

  /// 构建待办事项
  Widget _buildActionableItems(BuildContext context) =>
      Consumer3<ExpensePlanProvider, BudgetProvider, TransactionProvider>(
        builder: (context, expensePlanProvider, budgetProvider,
            transactionProvider, child) {
          final items = <ActionableItem>[];

          // 检查还款提醒
          final expensePlans = expensePlanProvider.activeExpensePlans;
          final now = DateTime.now();
          for (final plan in expensePlans) {
            // 计算下次付款日期
            DateTime? nextPaymentDate;
            if (plan.frequency == ExpenseFrequency.monthly) {
              // 每月付款，计算下个月同一天
              nextPaymentDate = DateTime(
                now.year,
                now.month + 1,
                plan.startDate.day,
              );
            } else if (plan.frequency == ExpenseFrequency.weekly) {
              // 每周付款
              final daysSinceStart = now.difference(plan.startDate).inDays;
              final weeksSinceStart = daysSinceStart ~/ 7;
              nextPaymentDate = plan.startDate.add(
                Duration(days: (weeksSinceStart + 1) * 7),
              );
            }

            if (nextPaymentDate != null) {
              final daysUntilPayment = nextPaymentDate.difference(now).inDays;
              if (daysUntilPayment >= 0 && daysUntilPayment <= 7) {
                items.add(
                  ActionableItem(
                    icon: Icons.payment_outlined,
                    title: '距离${plan.name}还款还有 $daysUntilPayment 天',
                    color: daysUntilPayment <= 3
                        ? const Color(0xFFF44336)
                        : Colors.orange,
                    onTap: () {
                      // TODO: 导航到还款详情
                    },
                  ),
                );
              }
            }
          }

          // 检查待清账交易
          final pendingReconciliation = transactionProvider.transactions
              .where((t) => t.status == TransactionStatus.pending)
              .length;
          if (pendingReconciliation > 0) {
            items.add(
              ActionableItem(
                icon: Icons.check_circle_outline,
                title: '有 $pendingReconciliation 笔交易待清账确认',
                color: const Color(0xFF2196F3),
                onTap: () {
                  // TODO: 导航到清账页面
                },
              ),
            );
          }

          // 检查工资到账提醒
          final salaryIncomes = budgetProvider.activeSalaryIncomes;
          if (salaryIncomes.isNotEmpty) {
            final today = DateTime.now();
            final dayOfMonth = today.day;
            // 假设工资在每月15号发放
            if (dayOfMonth >= 13 && dayOfMonth <= 15) {
              items.add(
                ActionableItem(
                  icon: Icons.account_balance_wallet_outlined,
                  title: '工资预计明日到账',
                  color: const Color(0xFF4CAF50),
                  onTap: () {
                    // TODO: 导航到工资管理
                  },
                ),
              );
            }
          }

          if (items.isEmpty) {
            return const SizedBox.shrink();
          }

          return AppCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  '待办事项',
                  style: AppTextStyles.headlineMedium(context),
                ),
                SizedBox(height: AppDesignTokens.spacing12),
                ...items.map((item) => _buildActionableItem(context, item)),
              ],
            ),
          );
        },
      );

  Widget _buildActionableItem(
    BuildContext context,
    ActionableItem item,
  ) =>
      InkWell(
        onTap: item.onTap,
        borderRadius: BorderRadius.circular(AppDesignTokens.borderRadius8),
        child: Padding(
          padding: EdgeInsets.symmetric(vertical: AppDesignTokens.spacing8),
          child: Row(
            children: [
              Container(
                padding: EdgeInsets.all(AppDesignTokens.spacing8),
                decoration: BoxDecoration(
                  color: item.color.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(AppDesignTokens.borderRadius8),
                ),
                child: Icon(
                  item.icon,
                  color: item.color,
                  size: AppDesignTokens.iconSizeMedium,
                ),
              ),
              SizedBox(width: AppDesignTokens.spacing12),
              Expanded(
                child: Text(
                  item.title,
                  style: AppTextStyles.bodyMedium(context).copyWith(
                    fontWeight: AppDesignTokens.fontWeightMedium,
                  ),
                ),
              ),
              Icon(
                Icons.chevron_right,
                color: AppDesignTokens.secondaryText(context),
                size: AppDesignTokens.iconSizeMedium,
              ),
            ],
          ),
        ),
      );

  /// 构建最近交易
  Widget _buildRecentTransactions(BuildContext context) =>
      Consumer<TransactionProvider>(
        builder: (context, transactionProvider, child) {
          final recentTransactions = transactionProvider.transactions
              .where((t) => t.status != TransactionStatus.draft)
              .toList()
            ..sort((a, b) => b.date.compareTo(a.date));

          final displayTransactions = recentTransactions.take(3).toList();

          return AppCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      '最近交易',
                      style: AppTextStyles.headlineMedium(context),
                    ),
                    TextButton(
                      onPressed: () {
                        // TODO: 导航到完整交易列表
                      },
                      child: Text(
                        '查看全部',
                        style: AppTextStyles.bodySmall(context).copyWith(
                          color: AppDesignTokens.primaryAction(context),
                        ),
                      ),
                    ),
                  ],
                ),
                SizedBox(height: AppDesignTokens.spacing12),
                if (displayTransactions.isEmpty)
                  AppEmptyStates.emptyList(
                    actionLabel: '添加交易',
                    onAction: () {
                      // TODO: 导航到添加交易
                    },
                  )
                else
                  ...displayTransactions.map((transaction) {
                    final isIncome = transaction.type == TransactionType.income ||
                        (transaction.type == null &&
                            transaction.category.isIncome);
                    final accountName = _getAccountName(
                      transaction.fromAccountId ?? '',
                    );

                    return Column(
                      children: [
                        ListTile(
                          contentPadding: EdgeInsets.zero,
                          leading: Container(
                            width: 40,
                            height: 40,
                            decoration: BoxDecoration(
                              color: (isIncome
                                        ? AppDesignTokens.successColor(context)
                                      : AppDesignTokens.errorColor)
                                  .withOpacity(0.1),
                              borderRadius: BorderRadius.circular(AppDesignTokens.borderRadius8),
                            ),
                            child: Icon(
                              isIncome ? Icons.trending_up : Icons.trending_down,
                              color: isIncome
                                        ? AppDesignTokens.successColor(context)
                                  : AppDesignTokens.errorColor,
                              size: AppDesignTokens.iconSizeMedium,
                            ),
                          ),
                          title: Text(
                            transaction.description,
                            style: AppTextStyles.bodyLarge(context).copyWith(
                              fontWeight: AppDesignTokens.fontWeightMedium,
                            ),
                          ),
                          subtitle: Text(
                            '${transaction.category.displayName} • $accountName',
                            style: AppTextStyles.bodySmall(context),
                          ),
                          trailing: Text(
                            context.formatAmount(
                              isIncome ? transaction.amount : -transaction.amount,
                            ),
                            style: AppTextStyles.bodyMedium(context).copyWith(
                              color: isIncome
                                        ? AppDesignTokens.successColor(context)
                                  : AppDesignTokens.errorColor,
                              fontWeight: AppDesignTokens.fontWeightSemiBold,
                            ),
                          ),
                          onTap: () {
                            Navigator.of(context).push<void>(
                              AppAnimations.createRoute<void>(
                                TransactionDetailScreen(
                                  transaction: transaction,
                                ),
                              ),
                            );
                          },
                        ),
                        if (displayTransactions.last != transaction)
                          Divider(height: 1),
                      ],
                    );
                  }),
              ],
            ),
          );
        },
      );

  String _getAccountName(String accountId) {
    try {
      final accountProvider = context.read<AccountProvider>();
      final account = accountProvider.accounts.firstWhere(
        (acc) => acc.id == accountId,
        orElse: () => throw StateError('Account not found: $accountId'),
      );
      return account.name;
    } catch (e) {
      return accountId.length > 8 ? accountId.substring(0, 8) : accountId;
    }
  }

  Future<void> _refreshData() async {
    await Future.wait<void>([
      context.read<AssetProvider>().loadAssets(),
      context.read<BudgetProvider>().initialize(),
      context.read<TransactionProvider>().initialize(),
      context.read<ExpensePlanProvider>().initialize(),
    ]);
  }
}

class ActionableItem {
  ActionableItem({
    required this.icon,
    required this.title,
    required this.color,
    required this.onTap,
  });

  final IconData icon;
  final String title;
  final Color color;
  final VoidCallback onTap;
}

