import 'package:equatable/equatable.dart';
import 'package:uuid/uuid.dart';

// 交易流向枚举 - 清晰定义资金流向
enum TransactionFlow {
  externalToWallet('外部->钱包'), // 收入
  walletToExternal('钱包->外部'), // 支出
  walletToWallet('钱包->钱包'), // 预算转移
  assetToWallet('资产->钱包'), // 资产变现
  walletToAsset('钱包->资产'); // 资产购入

  const TransactionFlow(this.displayName);
  final String displayName;

  static TransactionFlow fromDisplayName(String displayName) =>
      TransactionFlow.values.firstWhere(
        (e) => e.displayName == displayName,
        orElse: () =>
            throw ArgumentError('Unknown TransactionFlow: $displayName'),
      );

  // 向后兼容的映射
  static TransactionFlow fromLegacyType(TransactionType legacyType) {
    switch (legacyType) {
      case TransactionType.income:
        return TransactionFlow.externalToWallet;
      case TransactionType.expense:
        return TransactionFlow.walletToExternal;
      case TransactionType.transfer:
        return TransactionFlow.walletToWallet;
      default:
        throw ArgumentError(
            'Unsupported TransactionType for legacy mapping: $legacyType');
    }
  }

  // 新流向到旧类型的反向映射（用于向后兼容）
  static TransactionType? toLegacyType(TransactionFlow flow) {
    switch (flow) {
      case TransactionFlow.externalToWallet:
        return TransactionType.income;
      case TransactionFlow.walletToExternal:
        return TransactionType.expense;
      case TransactionFlow.walletToWallet:
        return TransactionType.transfer;
      case TransactionFlow.assetToWallet:
      case TransactionFlow.walletToAsset:
        // 资产交易在旧系统中没有对应的类型，返回null
        return null;
    }
  }
}

// 向后兼容的交易类型枚举
enum TransactionType {
  income('收入'),
  expense('支出'),
  transfer('转账');

  const TransactionType(this.displayName);
  final String displayName;

  static TransactionType fromDisplayName(String displayName) =>
      TransactionType.values.firstWhere(
        (e) => e.displayName == displayName,
        orElse: () =>
            throw ArgumentError('Unknown TransactionType: $displayName'),
      );
}

// 交易状态枚举
enum TransactionStatus {
  draft('草稿'),
  confirmed('已确认'),
  pending('待处理'),
  cancelled('已取消');

  const TransactionStatus(this.displayName);
  final String displayName;

  static TransactionStatus fromDisplayName(String displayName) =>
      TransactionStatus.values.firstWhere(
        (e) => e.displayName == displayName,
        orElse: () =>
            throw ArgumentError('Unknown TransactionStatus: $displayName'),
      );
}

// 交易分类枚举
enum TransactionCategory {
  // 收入分类
  salary('工资'),
  bonus('奖金'),
  investment('投资收益'),
  freelance('自由职业'),
  gift('礼金'),
  otherIncome('其他收入'),

  // 支出分类
  food('餐饮'),
  transport('交通'),
  shopping('购物'),
  entertainment('娱乐'),
  healthcare('医疗'),
  education('教育'),
  housing('住房'),
  utilities('水电费'),
  insurance('保险'),
  otherExpense('其他支出');

  const TransactionCategory(this.displayName);
  final String displayName;

  static TransactionCategory fromDisplayName(String displayName) =>
      TransactionCategory.values.firstWhere(
        (e) => e.displayName == displayName,
        orElse: () =>
            throw ArgumentError('Unknown TransactionCategory: $displayName'),
      );

  // 判断是否为收入分类
  bool get isIncome => [
        TransactionCategory.salary,
        TransactionCategory.bonus,
        TransactionCategory.investment,
        TransactionCategory.freelance,
        TransactionCategory.gift,
        TransactionCategory.otherIncome,
      ].contains(this);

  // 判断是否为支出分类
  bool get isExpense => [
        TransactionCategory.food,
        TransactionCategory.transport,
        TransactionCategory.shopping,
        TransactionCategory.entertainment,
        TransactionCategory.healthcare,
        TransactionCategory.education,
        TransactionCategory.housing,
        TransactionCategory.utilities,
        TransactionCategory.insurance,
        TransactionCategory.otherExpense,
      ].contains(this);
}

// 交易记录模型
class Transaction extends Equatable {
  Transaction({
    String? id,
    required this.description,
    required this.amount,
    // 新的交易流向（推荐使用）
    this.flow,
    // 向后兼容的旧类型
    this.type,
    required this.category,
    this.subCategory,
    // 钱包ID（from和to的语义根据flow确定）
    this.fromWalletId,
    this.toWalletId,
    // 资产ID（用于资产交易）
    this.fromAssetId,
    this.toAssetId,
    // 向后兼容的字段
    this.fromAccountId,
    this.toAccountId,
    this.envelopeBudgetId,
    required this.date,
    this.notes,
    this.tags = const [],
    this.status = TransactionStatus.confirmed,
    this.isRecurring = false,
    this.recurringRule,
    this.parentTransactionId,
    DateTime? creationDate,
    DateTime? updateDate,
    this.imagePath,
    this.isAutoGenerated = false,
  })  : id = id ?? const Uuid().v4(),
        creationDate = creationDate ?? DateTime.now(),
        updateDate = updateDate ?? DateTime.now() {
    // 验证参数一致性
    _validateTransaction();
  }

  // 验证交易参数
  void _validateTransaction() {
    // 如果使用新流向，检查必要字段
    if (flow != null) {
      switch (flow!) {
        case TransactionFlow.externalToWallet:
        case TransactionFlow.walletToExternal:
          // 需要钱包ID
          if (fromWalletId == null && toWalletId == null) {
            throw ArgumentError('钱包ID不能为空');
          }
          break;
        case TransactionFlow.walletToWallet:
          // 需要两个钱包ID
          if (fromWalletId == null || toWalletId == null) {
            throw ArgumentError('需要指定来源和目标钱包');
          }
          break;
        case TransactionFlow.assetToWallet:
        case TransactionFlow.walletToAsset:
          // 需要钱包ID和资产ID
          if ((fromWalletId == null && toWalletId == null) ||
              (fromAssetId == null && toAssetId == null)) {
            throw ArgumentError('需要指定钱包和资产');
          }
          break;
      }
    }
  }

  // 新的字段定义
  final String id;
  final String description;
  final double amount;
  final TransactionFlow? flow; // 新的交易流向
  final TransactionType? type; // 向后兼容
  final TransactionCategory category;
  final String? subCategory;

  // 钱包ID（新的推荐字段）
  final String? fromWalletId;
  final String? toWalletId;

  // 资产ID（用于资产交易）
  final String? fromAssetId;
  final String? toAssetId;

  // 向后兼容的字段
  final String? fromAccountId;
  final String? toAccountId;
  final String? envelopeBudgetId;

  final DateTime date;
  final String? notes;
  final List<String> tags;
  final TransactionStatus status;
  final bool isRecurring;
  final String? recurringRule;
  final String? parentTransactionId;
  final DateTime creationDate;
  final DateTime updateDate;
  final String? imagePath;
  final bool isAutoGenerated;

  // 反序列化
  factory Transaction.fromJson(Map<String, dynamic> json) {
    // 处理新的交易流向
    TransactionFlow? flow;
    if (json['flow'] != null) {
      try {
        flow = TransactionFlow.values.firstWhere(
          (e) => e.name == json['flow'] as String,
        );
      } catch (e) {
        // 如果找不到对应的枚举值，flow保持为null
      }
    }

    // 向后兼容：如果没有新字段，尝试从旧字段推断
    TransactionType? legacyType;
    if (json['type'] != null) {
      try {
        legacyType = TransactionType.values.firstWhere(
          (e) => e.name == json['type'] as String,
        );
      } catch (e) {
        // 如果找不到对应的枚举值，legacyType保持为null
      }
    }

    // 先解析category
    final TransactionCategory category = TransactionCategory.values.firstWhere(
      (e) => e.name == json['category'],
      orElse: () => throw ArgumentError(
          'Unknown TransactionCategory: ${json['category']}'),
    );

    // 如果legacyType为null，尝试根据category推断
    TransactionType? finalType = legacyType;
    if (finalType == null && category.isIncome) {
      finalType = TransactionType.income;
    } else if (finalType == null && !category.isIncome) {
      finalType = TransactionType.expense;
    }

    return Transaction(
      id: json['id'] as String,
      description: json['description'] as String,
      amount: (json['amount'] as num).toDouble(),
      flow: flow,
      type: finalType,
      category: category,
      subCategory: json['subCategory'] as String?,
      // 新的钱包ID字段
      fromWalletId: json['fromWalletId'] as String?,
      toWalletId: json['toWalletId'] as String?,
      fromAssetId: json['fromAssetId'] as String?,
      toAssetId: json['toAssetId'] as String?,
      // 向后兼容的字段
      fromAccountId: json['fromAccountId'] as String?,
      toAccountId: json['toAccountId'] as String?,
      envelopeBudgetId: json['envelopeBudgetId'] as String?,
      date: DateTime.parse(json['date'] as String),
      notes: json['notes'] as String?,
      tags: List<String>.from((json['tags'] as List<dynamic>?) ?? []),
      status: TransactionStatus.values.firstWhere(
        (e) => e.name == json['status'],
        orElse: () =>
            throw ArgumentError('Unknown TransactionStatus: ${json['status']}'),
      ),
      isRecurring: json['isRecurring'] as bool? ?? false,
      recurringRule: json['recurringRule'] as String?,
      parentTransactionId: json['parentTransactionId'] as String?,
      creationDate: DateTime.parse(json['creationDate'] as String),
      updateDate: DateTime.parse(json['updateDate'] as String),
      imagePath: json['imagePath'] as String?,
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
    );
  }

  // 复制并修改
  Transaction copyWith({
    String? id,
    String? description,
    double? amount,
    TransactionFlow? flow,
    TransactionType? type,
    TransactionCategory? category,
    String? subCategory,
    String? fromWalletId,
    String? toWalletId,
    String? fromAssetId,
    String? toAssetId,
    String? fromAccountId,
    String? toAccountId,
    String? envelopeBudgetId,
    DateTime? date,
    String? notes,
    List<String>? tags,
    TransactionStatus? status,
    bool? isRecurring,
    String? recurringRule,
    String? parentTransactionId,
    DateTime? creationDate,
    DateTime? updateDate,
    String? imagePath,
    bool? isAutoGenerated,
  }) =>
      Transaction(
        id: id ?? this.id,
        description: description ?? this.description,
        amount: amount ?? this.amount,
        flow: flow ?? this.flow,
        type: type ?? this.type,
        category: category ?? this.category,
        subCategory: subCategory ?? this.subCategory,
        fromWalletId: fromWalletId ?? this.fromWalletId,
        toWalletId: toWalletId ?? this.toWalletId,
        fromAssetId: fromAssetId ?? this.fromAssetId,
        toAssetId: toAssetId ?? this.toAssetId,
        fromAccountId: fromAccountId ?? this.fromAccountId,
        toAccountId: toAccountId ?? this.toAccountId,
        envelopeBudgetId: envelopeBudgetId ?? this.envelopeBudgetId,
        date: date ?? this.date,
        notes: notes ?? this.notes,
        tags: tags ?? this.tags,
        status: status ?? this.status,
        isRecurring: isRecurring ?? this.isRecurring,
        recurringRule: recurringRule ?? this.recurringRule,
        parentTransactionId: parentTransactionId ?? this.parentTransactionId,
        creationDate: creationDate ?? this.creationDate,
        updateDate: updateDate ?? DateTime.now(),
        imagePath: imagePath ?? this.imagePath,
        isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      );

  // 序列化
  Map<String, dynamic> toJson() => {
        'id': id,
        'description': description,
        'amount': amount,
        // 新的交易流向字段
        'flow': flow?.name,
        // 向后兼容的旧字段
        'type': type?.name ?? TransactionFlow.toLegacyType(flow!)?.name,
        'category': category.name,
        'subCategory': subCategory,
        // 新的钱包ID字段
        'fromWalletId': fromWalletId,
        'toWalletId': toWalletId,
        'fromAssetId': fromAssetId,
        'toAssetId': toAssetId,
        // 向后兼容的字段
        'fromAccountId': fromAccountId,
        'toAccountId': toAccountId,
        'envelopeBudgetId': envelopeBudgetId,
        'date': date.toIso8601String(),
        'notes': notes,
        'tags': tags,
        'status': status.name,
        'isRecurring': isRecurring,
        'recurringRule': recurringRule,
        'parentTransactionId': parentTransactionId,
        'creationDate': creationDate.toIso8601String(),
        'updateDate': updateDate.toIso8601String(),
        'imagePath': imagePath,
        'isAutoGenerated': isAutoGenerated,
      };

  @override
  List<Object?> get props => [
        id,
        description,
        amount,
        flow,
        type,
        category,
        subCategory,
        fromWalletId,
        toWalletId,
        fromAssetId,
        toAssetId,
        fromAccountId,
        toAccountId,
        envelopeBudgetId,
        date,
        notes,
        tags,
        status,
        isRecurring,
        recurringRule,
        parentTransactionId,
        creationDate,
        updateDate,
        imagePath,
        isAutoGenerated,
      ];
}
